export const rule={
  "perfectionist/sort-variable-declarations": [
    2,
    {
      type:      `natural`,
      order:     `desc`,
      ignoreCase:false,
    },
  ],
  "perfectionist/sort-union-types": [
    2,
    {
      type:      `natural`,
      order:     `desc`,
      ignoreCase:false,
      groups:    [],
    },
  ],
  "perfectionist/sort-switch-case": [
    2,
    {
      type:      `natural`,
      order:     `desc`,
      ignoreCase:false,
    },
  ],
  "perfectionist/sort-sets": [
    2,
    {
      type:      `natural`,
      order:     `desc`,
      ignoreCase:false,
      groupKind: `literals-first`,
    },
  ],
  "perfectionist/sort-objects": [
    2,
    {
      useConfigurationIf: {},
      type:               `natural`,
      styledComponents:   true,
      partitionByNewLine: false,
      partitionByComment: false,
      order:              `desc`,
      objectDeclarations: true,
      ignorePattern:      [],
      ignoreCase:         false,
      groups:             [],
      destructureOnly:    false,
      destructuredObjects:true,
      customGroups:       {},
    },
  ],
  "perfectionist/sort-object-types": [
    2,
    {
      type:              `natural`,
      partitionByNewLine:false,
      order:             `desc`,
      ignoreCase:        false,
      groups:            [],
      groupKind:         `optional-first`,
      customGroups:      {},
    },
  ],
  "perfectionist/sort-named-imports": [
    2,
    {
      type:       `natural`,
      order:      `desc`,
      ignoreCase: false,
      ignoreAlias:false,
      groupKind:  `types-first`,
    },
  ],
  "perfectionist/sort-named-exports": [
    2,
    {
      type:      `natural`,
      order:     `desc`,
      ignoreCase:false,
      groupKind: `types-first`,
    },
  ],
  "perfectionist/sort-modules": [
    2,
    {
      type:              `natural`,
      specialCharacters: `keep`,
      partitionByNewLine:false,
      partitionByComment:false,
      order:             `desc`,
      newlinesBetween:   `never`,
      locales:           `en-US`,
      ignoreCase:        false,
      groups:            [],
      customGroups:      [],
      alphabet:          ``,
    },
  ],
  "perfectionist/sort-maps": [
    2,
    {
      type:      `natural`,
      order:     `desc`,
      ignoreCase:false,
    },
  ],
  "perfectionist/sort-jsx-props": [
    2,
    {
      type:         `natural`,
      order:        `asc`,
      ignorePattern:[],
      ignoreCase:   false,
      groups:       [],
      customGroups: {},
    },
  ],
  "perfectionist/sort-intersection-types": [
    2,
    {
      type:      `natural`,
      order:     `desc`,
      ignoreCase:false,
      groups:    [],
    },
  ],
  "perfectionist/sort-interfaces": [
    2,
    {
      type:              `natural`,
      partitionByNewLine:false,
      order:             `desc`,
      ignorePattern:     [],
      ignoreCase:        false,
      groups:            [],
      groupKind:         `optional-first`,
      customGroups:      {},
    },
  ],
  "perfectionist/sort-imports": [
    2,
    {
      type:              `natural`,
      partitionByNewLine:false,
      partitionByComment:false,
      order:             `desc`,
      newlinesBetween:   0,
      internalPattern:   [
        `^~/.*`,
      ],
      ignoreCase:false,
      groups:    [
        `type`,
        [
          `builtin`,
          `external`,
        ],
        `internal-type`,
        `internal`,
        [
          `parent-type`,
          `sibling-type`,
          `index-type`,
        ],
        [
          `parent`,
          `sibling`,
          `index`,
        ],
        `object`,
        `unknown`,
      ],
      environment: `node`,
      customGroups:{
        value:{},
        type: {},
      },
    },
  ],
  "perfectionist/sort-heritage-clauses": [
    2,
    {
      type:             `natural`,
      specialCharacters:`keep`,
      order:            `desc`,
      locales:          `en-US`,
      ignoreCase:       false,
      groups:           [],
      customGroups:     {},
      alphabet:         ``,
    },
  ],
  "perfectionist/sort-exports": [
    2,
    {
      type:      `natural`,
      order:     `desc`,
      ignoreCase:false,
    },
  ],
  "perfectionist/sort-enums": [
    2,
    {
      type:              `natural`,
      partitionByComment:false,
      order:             `desc`,
      ignoreCase:        false,
    },
  ],
  "perfectionist/sort-decorators": [
    2,
    {
      type:              `natural`,
      specialCharacters: `keep`,
      sortOnProperties:  true,
      sortOnParameters:  true,
      sortOnMethods:     true,
      sortOnClasses:     true,
      sortOnAccessors:   true,
      partitionByComment:false,
      order:             `desc`,
      locales:           `en-US`,
      ignoreCase:        false,
      groups:            [],
      customGroups:      {},
      alphabet:          ``,
    },
  ],
  "perfectionist/sort-classes": [
    2,
    {
      type:              `natural`,
      partitionByComment:false,
      order:             `desc`,
      ignoreCase:        false,
      groups:            [
        `index-signature`,
        `static-property`,
        `protected-property`,
        `private-property`,
        `property`,
        `constructor`,
        `static-method`,
        `protected-method`,
        `private-method`,
        `method`,
        [
          `get-method`,
          `set-method`,
        ],
        `unknown`,
      ],
    },
  ],
  "perfectionist/sort-array-includes": [
    2,
    {
      type:      `natural`,
      order:     `desc`,
      ignoreCase:false,
      groupKind: `literals-first`,
    },
  ],
};
